name: build-github-pages
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          mkdir .public
          php index.php > .public/index.html
          php accordion.php > .public/accordion.html
          php animation.php > .public/animation.html
          php buttons.php > .public/buttons.html
          php content.php > .public/content.html
          php coronavirus.php > .public/coronavirus.html
          php forms.php > .public/forms.html
          php grid-system.php > .public/grid-system.html
          php icons.php > .public/icons.html
          php lists.php > .public/lists.html
          php logos.php > .public/logos.html
          php messages.php > .public/messages.html
          php metadata.php > .public/metadata.html
          php navigation.php > .public/navigation.html
          php pages.php > .public/pages.html
          php tables.php > .public/tables.html
          php typography.php > .public/typography.html
          php widgets.php > .public/widgets.html
          php videos.php > .public/videos.html
          cp -r * .public
          mv .public public

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: github-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
